AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: siemenTestE
      ImageId: ami-0889a44b331db0194
      InstanceType: t3a.small
      SubnetId: 
        Ref: siemensubnet
      SecurityGroupIds:
        - Ref: siemensg
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo yum -y install curl
          curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
          sudo yum update -y
          sudo yum install -y nodejs git
          sudo yum -y install gcc-c++ make
          mkdir -p /home/ec2-user/app && cd /home/ec2-user/app
          git clone https://bitbucket.org/siemens-disw-dp/character-creator.git
          yum install iptables-services -y
          systemctl enable iptables
          systemctl start iptables
          sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 3000
          sudo npm install #
          npm start
      Tags:
        - Key: "Name"
          Value: "EC2SiemenTest"
  siemensg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "SGSiemenTest"
      GroupDescription: "Siemen Test SG"
      VpcId: 
        Ref: siemenTestVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0  
      SecurityGroupEgress:
        - Description: "Allow all outbound traffic"
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: "SGSiemenTest"
  siemenTestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.10.0/24
      EnableDnsSupport: true
      Tags:
        - Key: "Name"
          Value: "VPCSiemenTest"
  siemensubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      VpcId: 
        Ref: siemenTestVPC
      CidrBlock: 10.10.10.0/25
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Name"
          Value: "SubnetSiemenTest"
  siemenrtable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: 
        Ref: siemenTestVPC
      Tags:
        - Key: "Name"
          Value: "RTSiemenTest"
  routeName:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: 
        Ref: siemenrtable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: 
        Ref: siemenigw
  siemenigw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: "Name"
          Value: "IGWSiemenTest"
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: 
        Ref: siemenTestVPC
      InternetGatewayId:
        Ref: siemenigw
  siemenrtassoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: 
        Ref: siemenrtable
      SubnetId: 
        Ref: siemensubnet
  

